Add docs for configuring babeljs
ember-cli/ember-cli.github.io pull request #112
Opened 2016-12-03 12:10 UTC by cibernox

Has an example of how to disable certain ES6 transformations and links to babel 5.X docs for a comprehensive list of options and transformations.

2016-12-03 12:12 UTC, cibernox commented
Part of Quest in https://github.com/ember-cli/ember-cli.github.io/issues/111

2016-12-03 17:03 UTC, stefanpenner requested changes

2016-12-03 17:03 UTC, stefanpenner commented on _posts/2013-04-09-asset-compilation.md
> +Ember-cli automatically transpiles future javascript (ES6/ES2015, ES2016 and beyond) into standard ES5
- [ ] We should briefly outline that this is using babel 5 (i saw you provided links to the appropriate docs, awesome)
- [ ]  We should point to the babel 6 meta issue, for progress getting to babel 6. For those who will likely be immediately curious

2016-12-03 17:03 UTC, stefanpenner commented
looks good, some small notes above

2016-12-03 17:39 UTC, cibernox commented on _posts/2013-04-09-asset-compilation.md
> +Ember-cli automatically transpiles future javascript (ES6/ES2015, ES2016 and beyond) into standard ES5
@stefanpenner [This](https://github.com/ember-cli/ember-cli/issues/5015) issue?

2016-12-04 02:35 UTC, stefanpenner approved these changes

2016-12-04 02:36 UTC, stefanpenner commented
@cibernox awesome, thanks sir!

2016-12-04 02:36 UTC, merged