Update 2013-04-08-generators-and-blueprints
ember-cli/ember-cli.github.io pull request #157
Opened 2017-07-08 21:09 UTC by villander

Improve Ember syntax with best practices and ES6

2017-07-08 21:53 UTC, villander commented
@stefanpenner look this, please =D

2017-07-08 22:20 UTC, kellyselden requested changes

2017-07-08 22:20 UTC, kellyselden commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +isDevelopingAddon: () => true
These should match the blueprint:

```
isDevelopingAddon() {
  return true;
}
```

2017-07-08 22:47 UTC, villander commented
I fixed your review @kellyselden, thanks man

2017-07-16 18:15 UTC, kellyselden requested changes

2017-07-16 18:15 UTC, kellyselden commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  isDevelopingAddon: () => true
can you revert arrow syntax, because `this` has meaning here.

2017-07-16 18:15 UTC, kellyselden commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  didInsertElement() {
@locks Can you confirm this is the best practice for didInsertElement?

2017-07-16 18:17 UTC, locks commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  didInsertElement() {
Confirm, you should avoid using the lifecycle events and instead override the hooks.

2017-07-16 18:18 UTC, stefanpenner commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  isDevelopingAddon: () => true
👍 

also, concise function could be used:

```
isDevelopingAddon() {
  return true;
}
```

2017-07-17 14:44 UTC, villander commented
@kellyselden i think that all now are done =D

2017-07-17 18:22 UTC, kellyselden requested changes
one last thing

2017-07-17 18:22 UTC, kellyselden commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  }
missing comma

2017-07-17 18:23 UTC, villander commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  }
hehe

2017-07-17 18:50 UTC, villander commented on _posts/2013-04-06-developing-addons-and-blueprints.md
> +  }
Fixed man

2017-07-17 18:56 UTC, kellyselden approved these changes

2017-07-17 18:57 UTC, kellyselden commented
Thanks for this!

2017-07-17 18:57 UTC, merged